
setup:
    sudo apt-get update
    sudo apt-get install swig

run:
    swig -outdir wrapper/ -python  -o wrapper/gfg_wrap.c gfg.i
    cd wrapper && gcc -c -fpic gfg_wrap.c ../gfg.c -I/usr/include/python3.8
    cd wrapper && gcc -shared gfg.o gfg_wrap.o -o _gfg.so

    python3 app.py
