_default:
  @just --list --unsorted

test:
  #!/bin/bash
  for d in $(find . -type d); do
    pushd $d > /dev/null
      v test .
    popd > /dev/null
  done

format:
  #!/bin/bash
  for d in $(find . -type d); do
    pushd $d > /dev/null
      v fmt -w .
    popd > /dev/null
  done